name: Python Latest Image

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  REGISTRY: ghcr.io
  NAME: jjaychinn 
  IMAGE_TAG: ghcr.io/jjaychinn/pythonsmart:latest
  GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}

jobs:
  build-image:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t ${IMAGE_TAG} .
      - name: Push python Image
        if: ${{ github.event_name == 'push' }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ${REGISTRY} -u ${NAME} --password-stdin
          docker push ${IMAGE_TAG}
